config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  devise_for :users
  resources :products do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(text: params[:text], product_id: params[:product_id], user_id: current_user.id)
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:product_id]) }
      format.json
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :login, only: [:new]
  def index
    @products = Product.order("created_at DESC").limit(10)
    @news = News.order("created_at DESC").limit(10)
  end

  def new

  end

  def create
    Product.create(product_params)
    redirect_to root_path
  end

  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.includes(:user)
  end

  private
  def product_params
    params.permit(:title, :product_url, :text).merge(user_id: current_user.id)
  end

  def login
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    require "redcarpet"
    require "coderay"

    class HTMLwithCoderay < Redcarpet::Render::HTML
        def block_code(code, language)
            language = language.split(':')[0]

            case language.to_s
            when 'rb'
                lang = 'ruby'
            when 'yml'
                lang = 'yaml'
            when 'css'
                lang = 'css'
            when 'html'
                lang = 'html'
            when ''
                lang = 'md'
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/curriculums_helper.rb
module CurriculumsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>広告共有SNSサービス</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.10/vue.js'></script>
  </head>

  <body>
    <header>
      <div class="header__logo"><a href="/"><%= image_tag 'hitokuse_logo.png', class: 'header__logo' %></a></div>
      <div class="account">
        <% unless user_signed_in? %>
          <div class="list"><%= link_to 'ログイン', new_user_session_path %></div>
          <div class="list"><%= link_to '新規登録', new_user_registration_path %></div>
        <% else %>
          <div class="list"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: {confirm: 'ログアウトしますか?'} %></div>
          <div class="list"><span class="fa fa-fw fa-pencil-square-o mr-1"></span><%= link_to '投稿する', new_product_path %></div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/products/_news.html.erb
<% @news.each do |news| %>
  <div class="trend 2">
    <ul class="trend__ranking">
      <li class="title__news"><%= news.title %></li>
      <li class="name"><%= news.content %></li>
      <li class="news_url"><a href="<%= news.news_url %>"><%= news.news_url %></a></li>
      <li class="other"><%= news.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></li>
    </ul>
  </div>
<% end %>

app/views/products/_product.html.erb
<% @products.each do |product| %>
  <div class="trend 1 active">
    <ul class="trend__ranking">
      <li class="image"><%= product.product_url.html_safe %></li>
      <li class="title"><%= product.title %></li>
      <li class="user_text"><%= markdown(product.text).html_safe %></li>
      <li class="name">by <%= product.user.name %></li>
      <li class="other"><%= product.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></li>
      <li class="other"><i class="fa fa-thumbs-up"></i></li>
      <li class="other"><a href="/products/<%= product.id %>"><i class="fa fa-reply"></i></a></li>
    </ul>
  </div>
<% end %>

app/views/products/index.html.erb
<div class="content">
  <h1>Ads Together</h1>
  <div class="text">
    <p>広告を見て楽しむ、シェアするSNSサイト</p>
  </div>
</div>

<div class="curriculums">
  <div class="curriculums__nav">
    <div class="curriculums__nav__title">
      <i class="fa fa-line-chart mr-1">トレンド</i>
      <p class="title-text">人気の広告を毎日更新</p>
    </div>
    <div class="ChangeElem_Btn_Content flex-box">
      <p class="ChangeElem_Btn product" id="ads">広告</p>
      <p class="ChangeElem_Btn news" id="news">ニュース</p>
      <p class="ChangeElem_Btn like" id="like">いいね</p>
    </div>
  </div>
  <li class="ChangeElem_Panel">
    <%= render 'product' %>
  </li>
  <li class="ChangeElem_Panel">
    <%= render 'news' %>
  </li>
  <li class="ChangeElem_Panel">
    <%= render 'product' %>
  </li>
</div>

app/views/products/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- UI Kit -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/js/uikit.min.js"></script>

    <!-- Codemirror and marked dependencies -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/codemirror.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/codemirror.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/markdown/markdown.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/addon/mode/overlay.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/xml/xml.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.38.0/mode/gfm/gfm.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.js'></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML editor CSS and JavaScript -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/css/components/htmleditor.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.5/js/components/htmleditor.js"></script>

  </head>
  <body data-turbolinks="false">
    <div class="form_wrapper">
      <%= form_tag('/products', method: :post) do %>
        <input name="title" placeholder="タイトル" type="text" class="form_title">
        <input name="product_url" placeholder="タグ貼り付け(HTML)" type="text" class="form_title">
        <textarea name="text" type="text" data-uk-htmleditor="{markdown:true}"># Write Something Here!</textarea>
        <input type="submit" class="submit" value="投稿する" redirect_to root_path>
      <% end %>
    </div>
  </body>
</html>

app/views/products/show.html.erb
<div class="ranking">
  <div class="user_title">
    <div class="user_date">
      <%= image_tag "snoopy.png", class: "user_image" %>
      <div class="user_name"><a href="/users/<%= @product.user.id %>"><%= @product.user.name %></a></div>
      <div class="user_post"><%= @product.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></div>
    </div>
    <h2 class="tweet_title"><%= @product.title %></h2>
  </div>
  <div class="product_url">
    <%= @product.product_url.html_safe %>
  </div>
  <div class="user_text">
    <%= markdown(@product.text).html_safe %>
  </div>
  <div class="container">
    <% if current_user %>
      <%= form_tag("/products/#{@product.id}/comments", method: :post, id: "new_comment") do %>
        <textarea cols="30" name="text" rows="2" class="textbox"></textarea>
        <input type="submit" class="comment-btn" name="SENT">
      <% end %>
    <% end %>
    <div class="comments">
      <% if @comments %>
        <% @comments.each do |comment| %>
          <p>
            <strong><%= comment.user.name %></strong>
            <%= comment.text %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>